[package]
name = "hypertext"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
log = "*"
pretty_env_logger = "*"
walkdir = "2"
handlebars = "3"
regex = "1"
serde = "*"
serde_derive = "*"
toml = "*"
Inflector = "*"
mdbook = "0.3.7"
pulldown-cmark = { version = "0.7", default-features = false, features = ["simd"] }
