[package]
name = "hypertext"
version = "0.8.0"
authors = ["muji <muji@tmpfs.org>"]
description = "Fast and lean static site generator"
repository = "https://github.com/tmpfs/hypertext"
edition = "2018"

[dependencies]
rand = "*"
chrono = "*"
open = "1.1"
structopt = "*"
log = "*"
pretty_env_logger = "*"
Inflector = "*"
handlebars = {version = "3.0", default-features = true, features = [ "dir_source" ] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "*"
serde_json = "1"
ignore = "0.4"
toml = "0.5.1"
rust-embed = "5.5.1"
human_bytes = "0.2.1"
zip = "0.5.5"
# html5ever = "0.23"
lazy_static = "1"
mdbook = { version = "0.3.7", default-features = false, features = [ "output" ] }
pulldown-cmark = { version = "0.6.1", default-features = false, features = ["simd"] }

# Watch feature
notify = { version = "4.0", optional = true }
# gitignore = { version = "1.0", optional = true }

# Serve feature
futures-util = { version = "0.3.4", optional = true }
tokio = { version = "0.2.18", features = ["macros"], optional = true }
warp = { version = "0.2.2", default-features = false, features = ["websocket"], optional = true }

[features]
default = ["watch", "serve"]
watch = ["notify"]
serve = ["futures-util", "tokio", "warp"]
