[package]
name = "hypertext"
version = "0.17.3"
authors = ["muji <muji@tmpfs.org>"]
description = "Fast and lean static site generator"
repository = "https://github.com/hypertext-live/hypertext"
edition = "2018"
default-run = "ht"

[dependencies]
rand = "0.7.3"
url = "2"
home = "0.5"
git2 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
open = "1.1"
structopt = "*"
log = "*"
pretty_env_logger = "*"
Inflector = "*"
handlebars = {version = "3.0", default-features = true, features = [ "dir_source" ] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "*"
serde_with = "1.4.0"
serde_json = "1"
ignore = "0.4"
toml = "0.5.1"
human_bytes = "0.2.1"
slug = "0.1.4"
lazy_static = "1"
mdbook = { version = "0.3.7", default-features = false, features = [ "output" ] }
pulldown-cmark = { version = "0.6.1", default-features = false, features = ["simd"] }
fluent-templates = {version = "0.5.9", default-features = true, features = ["handlebars"]}
unic-langid = "0.9.0"
rpassword = "4.0"
edit = "0.1"
semver = "0.10"
reqwest = { version = "0.10", features = ["blocking", "json"] }

#futures = "0.3.5"
#tokio-core = "0.1"
mime_guess = "2.0"
md-5 = "0.9.0"
rusoto_core = "0.44.0"
rusoto_signature = "0.44.0"
rusoto_s3 = "0.44.0"
tokio-util = { version = "0.3", default-features = false, features = ["codec"] }
bytes = "0.5"

# Watch feature
notify = { version = "4.0.0", optional = true }
# gitignore = { version = "1.0", optional = true }

# Serve feature
futures-util = { version = "0.3.4", optional = true }
tokio = { version = "0.2.18", features = ["macros"], optional = true }
warp = { version = "0.2.2", default-features = false, features = ["websocket"], optional = true }

[features]
default = ["watch", "serve"]
watch = ["notify"]
serve = ["futures-util", "tokio", "warp"]

[profile.release]
lto = true
codegen-units = 1

[package.metadata.bundle.bin.ht]
name = "ht"
identifier = "live.hypertext"
