[package]
name = "hypertext"
version = "0.17.4"
authors = ["muji <muji@tmpfs.org>"]
description = "Fast and lean static site generator"
repository = "https://github.com/hypertext-live/hypertext"
edition = "2018"
default-run = "ht"

[workspace]
members = [
  "components/extras/bundle",
  "components/extras/bundler",
  "components/cache",
  "components/compiler",
  "components/config",
  "components/content",
  "components/dirs",
  "components/git",
  "components/installer",
  "components/locale",
  "components/preference",
  "components/publisher",
  "components/report",
  "components/server",
  "components/updater",
  "components/utils",
]

[dependencies]
cache = {version = "0.1", path = "components/cache" }
compiler = {version = "0.1", path = "components/compiler" }
config = {version = "0.1", path = "components/config" }
content = {version = "0.1", path = "components/content" }
dirs = {version = "0.1", path = "components/dirs" }
git = {version = "0.1", path = "components/git" }
locale = {version = "0.1", path = "components/locale" }
preference = {version = "0.1", path = "components/preference" }
publisher = {version = "0.1", path = "components/publisher" }
report = {version = "0.1", path = "components/report" }
server = {version = "0.1", path = "components/server" }
updater = {version = "0.1", path = "components/updater" }
utils = {version = "0.1", path = "components/utils" }

thiserror = "1"
rand = "0.7.3"
url = "2"
git2 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
open = "1.1"
structopt = "0.3"
log = "0.4.8"
pretty_env_logger = "0.4"
Inflector = "0.11"
handlebars = {version = "3.0", default-features = true, features = [ "dir_source" ] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1"
serde_with = "1.4"
serde_json = "1"
ignore = "0.4"
toml = "0.5"
human_bytes = "0.2.1"
slug = "0.1.4"
lazy_static = "1"
unic-langid = "0.9.0"
semver = "0.10"

futures-util = { version = "0.3.4" }
tokio = { version = "0.2.18", features = ["macros"] }
warp = { version = "0.2.2", default-features = false, features = ["websocket"] }

[profile.release]
lto = true
codegen-units = 1
