[package]
name = "hypertext"
version = "0.5.0"
authors = ["muji <muji@tmpfs.org>"]
description = "Fast static site generator with mdbook support"
repository = "https://github.com/tmpfs/hypertext"
edition = "2018"

[dependencies]
structopt = "*"
log = "*"
pretty_env_logger = "*"
Inflector = "*"
handlebars = {version = "3.0", default-features = true, features = [ "dir_source" ] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "*"
serde_json = "1"
ignore = "0.4"
toml = "0.5.1"
# html5ever = "0.23"
lazy_static = "1"
mdbook = { version = "0.3.7", default-features = false, features = [ "output" ] }
pulldown-cmark = { version = "0.6.1", default-features = false, features = ["simd"] }

