[package]
name = "hypertext"
version = "0.3.0"
authors = ["muji <muji@tmpfs.org>"]
description = "Fast static site generator with mdbook support"
repository = "https://github.com/tmpfs/hypertext"
edition = "2018"

[dependencies]
structopt = "*"
log = "*"
pretty_env_logger = "*"
Inflector = "*"
walkdir = "2"
handlebars = {version = "3.0", default-features = true, features = [ "dir_source" ] }
regex = "1.0.0"
gitignore = "1.0.6"
toml = "0.5.1"
minify = "1.1"
mdbook = { version = "0.3.7", default-features = false, features = [ "output" ] }
pulldown-cmark = { version = "0.6.1", default-features = false, features = ["simd"] }
