[package]
name = "scm"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
utils = {version = "0.1", path = "../utils" }

thiserror = "1"
log = "0.4.8"
pbr = "1.0.3"

[dependencies.git2]
version = "0.13"
features = ["vendored-openssl"]
