[site]
description = "Fast and elegant site generator"
keywords = "Fast, Static, Website, Generator, Markdown, Handlebars, Mdbook, Rust"
repo_url = "https://github.com/tmpfs/hypertext"

["index"]
title = "Home"

["docs/index"]
title = "Documentation"

["install/index"]
digest_url = "https://github.com/tmpfs/hypertext/blob/master/sha256.txt"
