[package]
name = "bundle"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
bundler = { version = "0.1", path = "../bundler" }

structopt = "0.3"
log = "0.4.8"
pretty_env_logger = "0.4"

[[bin]]
path = "src/main.rs"
name = "ht-bundle"

