lang = "en"
host = "localhost"

[dependencies."std::core"]
version = "^5"

[dependencies."std::core".apply]
styles = ["**"]

[page.meta]
description = "Universal Web Editor"
keywords = "Web, Editor"

[build]
extend = ["html"]

[minify.html]
profiles = false

[sitemap]
profiles = false

[robots]
profiles = false
