lang = "en"
host = "localhost"

[dependencies."std::core"]
version = "^5"

[page.meta]
description = "Universal Web Editor"
keywords = "Web, Editor"

[build]
extend = ["html"]

[script]
src = "/assets/scripts/main.js"
dynamic = true

[[hook]]
command = "./build.sh"
#command = "npm"
#args = ["run", "build"]
  #"scripts": {
    #"build": "esbuild --define:process.env.NODE_ENV=\"'production'\"  ${BUILD_SOURCE}/src/main.jsx --bundle --outfile=${BUILD_TARGET}/assets/scripts/main.js --jsx-factory=h --jsx-fragment=Fragment"
  #},
files = ["src/*.js", "src/*.jsx"]
watch = true

[minify.html]
profiles = false

[sitemap]
profiles = false

[robots]
profiles = false
