lang = "en"
host = "localhost"

[dependencies."std::core"]
version = "^5"

#[dependencies."std::core".apply]
#styles = ["**"]

[page.meta]
description = "Universal Web Editor"
keywords = "Web, Editor"

[build]
extend = ["html"]

[script]
src = "/assets/scripts/main.js"
dynamic = true
#type = "module"

[[hook]]
command = "npm"
args = ["run", "build"]
files = ["src/*.js", "src/*.jsx"]
watch = true

[minify.html]
profiles = false

[sitemap]
profiles = false

[robots]
profiles = false
