[package]
name = "publisher"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
report = {version = "0.1", path = "../report" }

thiserror = "1"
log = "*"

mime_guess = "2.0"
md-5 = "0.9.0"
rusoto_core = "0.44.0"
rusoto_signature = "0.44.0"
rusoto_s3 = "0.44.0"
tokio = { version = "0.2.18", features = ["macros"] }
tokio-util = { version = "0.3", default-features = false, features = ["codec"] }
bytes = "0.5"

futures-util = { version = "0.3.4" }
