[package]
name = "compiler"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
book = {version = "0.1", path = "../book" }
collator = {version = "0.1", path = "../collator" }
config = {version = "0.1", path = "../config" }
datasource = {version = "0.1", path = "../datasource" }
frontmatter = {version = "0.1", path = "../frontmatter" }
livereload = {version = "0.1", path = "../livereload" }
loader = {version = "0.1", path = "../loader" }
locale = {version = "0.1", path = "../locale" }
minify = {version = "0.1", path = "../minify" }
utils = {version = "0.1", path = "../utils" }

thiserror = "1"
log = "0.4.8"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.4"
serde_json = "1"
ignore = "0.4"
toml = "0.5"
handlebars = {version = "3.0", default-features = true, features = [ "dir_source" ] }
slug = "0.1.4"
rand = "0.7.3"
chrono = { version = "0.4", features = ["serde"] }
pulldown-cmark = { version = "0.7", default-features = false, features = ["simd"] }
fluent-templates = {version = "0.5.9", default-features = true, features = ["handlebars"]}

notify = { version = "4.0.0" }
futures-util = { version = "0.3.4" }
tokio = { version = "0.2.18", features = ["macros"] }
warp = { version = "0.2.2", default-features = false, features = ["websocket"] }

once_cell = "1.4"
