[package]
name = "installer"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
updater = {version = "0.1", path = "../updater" }

log = "0.4.8"
pretty_env_logger = "0.4"
structopt = "0.3"

[[bin]]
path = "src/main.rs"
name = "hypertext-installer"
