[package]
name = "config"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
utils = {version = "0.1", path = "../utils" }

chrono = { version = "0.4", features = ["serde"] }
log = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_with = "1.4.0"
thiserror = "1"
toml = "0.5.1"
unic-langid = "0.9.0"
url = "2"
