[package]
name = "server"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
config = { version = "0.1", path = "../config" }
livereload = { version = "0.1", path = "../livereload" }
workspace = { version = "0.1", path = "../workspace" }
utils = { version = "0.1", path = "../utils" }

thiserror = "1"
log = "0.4.8"
url = "2"
open = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures-util = { version = "0.3.4" }
once_cell = "1.4"
libc = "0.2"

tokio = { version = "0.2.22", features = ["rt-core", "rt-threaded", "fs"] }
warp = { version = "0.2.5", features = ["tls", "websocket"] }
notify = { version = "5.0.0-pre.4" }
