[package]
name = "server"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
config = { version = "0.1", path = "../config" }
utils = { version = "0.1", path = "../utils" }

thiserror = "1"
log = "0.4.8"
open = "1.1"
serde = { version = "1.0", features = ["derive"] }
futures-util = { version = "0.3.4" }
tokio = { version = "0.2.22", features = ["full"] }
#warp = { version = "0.2.4", features = ["tls", "websocket"] }
warp = { features = ["tls", "websocket"], path = "/home/muji/git/warp" }
once_cell = "1.4"
