[package]
name = "server"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
utils = { version = "0.1", path = "../utils" }

log = "*"
serde = { version = "1.0", features = ["derive"] }
futures-util = { version = "0.3.4" }
tokio = { version = "0.2.18", features = ["macros"] }
warp = { version = "0.2.3" }

