[package]
name = "book"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
config = {version = "0.1", path = "../config" }

thiserror = "1"
log = "0.4.8"
mdbook = { version = "0.3.7", default-features = false, features = [ "output" ] }
