[package]
name = "runtime"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
config = {version = "0.1", path = "../config" }
datasource = {version = "0.1", path = "../datasource" }

once_cell = "1.4"
